version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: spring-mysql
    environment:
      MYSQL_ROOT_PASSWORD: banana
    volumes:
      - mysqldatavolume:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"

volumes:
  mysqldatavolume:
